AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - !ruby/regexp /old_and_unused\.rb$/

Documentation:
  Enabled: false

LineLength:
  Max: 99

ClassAndModuleChildren:
  Enabled: false